# cloudbuild.yaml
steps:
  # 1️⃣ Construir imagem Docker de treinamento
  - id: build-training-image
    name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/mlops-rohem/mlops/train:${SHORT_SHA}",
        "./training"
      ]

  # 2️⃣ Publicar imagem no Artifact Registry
  - id: push-training-image
    name: gcr.io/cloud-builders/docker
    waitFor: ['build-training-image']
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/mlops-rohem/mlops/train:${SHORT_SHA}"
      ]

  # 3️⃣ Submeter pipeline no Vertex AI
  - id: submit-vertex-pipeline
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: ['push-training-image']
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        python scripts/submit_pipeline.py \
          --image-uri=us-central1-docker.pkg.dev/mlops-rohem/mlops/train:${SHORT_SHA}
          --project-id=mlops-rohem \
options:
  logging: CLOUD_LOGGING_ONLY