steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/mlops-rohem/mlops/train:${SHORT_SHA}',
        './training'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/mlops-rohem/mlops/train:${SHORT_SHA}'
      ]

  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       python scripts/submit_pipeline.py
options:
  logging: CLOUD_LOGGING_ONLY